### ISSUE TITLE
HttpUtil这个类建议优化下

### ISSUE THREAD

**Issue by PossibleZero** [gengqiquan/HttpUtil#2]
最近准备写个网络库，这个整体写的比较容易理解，HttpUtil这个类冗余度有点高，可以适当的优化下，做成一个便于维护的库。

**Comment by gengqiquan** [comment]
@PossibleZero 很抱歉，这个库是针对公司的几个项目需求进行封装的，对于多变的别的项目需求来讲显得过度封装了。曾经想过提高开放性作为一个公共库。但是考虑到retrofit本身就是高度可自定义的。包裹着一个高开发性的框架去形成一个开放库不怎么明智，所以最终将这个封装库只作为一种针对需求的封装思路共享开来。

**Comment by PossibleZero** [comment]
嗯嗯明白了，不过已经很棒了，实现了业务与逻辑的剥离，给我提供了一些写网络框架的思路，谢谢啦。

**Comment by PossibleZero** [comment]
再请教一个问题，请求的时候以Call返回时，你用了集合来存储每次请求，请求成功与否都进行了移除，统一管理；但是在用Observable返回时，后面的操作都没有进行完全，是因为后面的操作类似没有做统一管理嘛？

**Comment by gengqiquan** [comment]
@PossibleZero Observable的机制和call完全不一样，在于订阅。在需要的地方取消订阅就可以了，详细的原理可以去研究下rxjava
